[application]
name = "Mi Rectificación MX"
default_platform = "desktop"
out_dir = "dist"

[web.app]
title = "Mi Rectificación MX"

[bundle]
identifier = "mx.mirectificacion.app"
publisher = "Mi Rectificación MX"
file_version = "0.1.0.2"
icon = [
    "../../assets/icons/32x32.png",
    "../../assets/icons/128x128.png",
    "../../assets/icons/128x128@2x.png",
    "../../assets/icons/icon.icns",
    "../../assets/icons/icon.ico",
]

[bundle.macos]
bundle_name = "Mi Rectificación MX"
