[package]
name = "mi-rectificacion-documents"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
chrono.workspace = true
lopdf.workspace = true
mi-rectificacion-domain = { path = "../domain" }
printpdf.workspace = true
rust_decimal.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tiny-skia.workspace = true
zip.workspace = true

[dev-dependencies]
image.workspace = true
rust_decimal.workspace = true
uuid.workspace = true
